bitbag_shopware_app_system:
  resource: '@BitBagShopwareAppSystemBundle/Resources/config/routes.yaml'

send_order:
  methods: ['POST']
  path: /app/send-order
  controller: bitbag.shopware_dhl_app.controller.order

api_settings:
  methods: ['GET', 'POST']
  path: /app/api-settings
  controller: bitbag.shopware_dhl_app.controller.api_settings

show_label:
  methods: ['GET']
  path: /app/show-label
  controller: bitbag.shopware_dhl_app.controller.show_label

get_label:
  methods: ['POST', 'GET']
  path: /app/get-label
  controller: bitbag.shopware_dhl_app.controller.get_label

check_credentials:
  methods: ['POST']
  path: /app/api-check-credentials
  controller: bitbag.shopware_dhl_app.controller.check_credentials
