registration:
  methods: ['GET']
  path: /app/registration
  controller: bitbag.shopware_app_skeleton.app_system.controller.registration_controller

confirm_registration:
  methods: ['POST']
  path: /app/registration/confirm
  controller: bitbag.shopware_skeleton_app.app_system.controller.confirmation_controller

app_lifecycle:
  resource: './lifecycle_routes.yaml'
  prefix: /app/lifecycle
  methods: ['POST']
  name_prefix: app_lifecycle_

send_order:
  methods: ['POST']
  path: /app/send-order
  controller: bitbag.shopware_dhl_app.controller.order

api_settings:
  methods: ['GET', 'POST']
  path: /app/api-settings
  controller: bitbag.shopware_dhl_app.controller.api_settings

show_label:
  methods: ['GET']
  path: /app/show-label
  controller: bitbag.shopware_dhl_app.controller.show_label

get_label:
  methods: ['GET']
  path: /app/get-label
  controller: bitbag.shopware_dhl_app.controller.get_label
